In [1]:
import pandas as pd

In [2]:
reranked_metrics = pd.read_csv('/Users/tusharrohilla/Desktop/natural_language_search_engine/eval_data/reranked_results/overall_metrics.csv')

In [3]:
retrival_metrics = pd.read_csv('/Users/tusharrohilla/Desktop/natural_language_search_engine/eval_data/results/overall_metrics.csv')

In [4]:
reranked_metrics

          metric     value
0         ndcg@5  0.893947
1          mrr@5  0.945833
2       recall@5  0.245144
3    precision@5  0.960000
4     hit_rate@5  0.975000
5        ndcg@10  0.902477
6         mrr@10  0.945833
7      recall@10  0.489281
8   precision@10  0.957500
9    hit_rate@10  0.975000
10       ndcg@20  0.938605
11        mrr@20  0.945833
12     recall@20  0.975000
13  precision@20  0.955000
14   hit_rate@20  0.975000

In [5]:
retrival_metrics

          metric     value
0         ndcg@5  0.820022
1          mrr@5  0.958333
2       recall@5  0.244829
3    precision@5  0.960000
4     hit_rate@5  0.975000
5        ndcg@10  0.856823
6         mrr@10  0.958333
7      recall@10  0.491598
8   precision@10  0.962500
9    hit_rate@10  0.975000
10       ndcg@20  0.913969
11        mrr@20  0.958333
12     recall@20  0.975000
13  precision@20  0.955000
14   hit_rate@20  0.975000