In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/tusharrohilla/Desktop/natural_language_search_engine/eval_data/evaluation_data.csv')

In [3]:
df.head()

,query_id,query,query_type,rank,score,id,parent_asin,title,brand,price,rating,rating_count,categories,image_url,document,relevance
0,1,wireless gaming mouse,exact,1,0.788320,c8e08be5-ec7e-4ff4-846a-fa3dd40fddd9,B006VP9R6Q,Cool Dealheroes 2.4G Wireless PC game Mouse Fo...,Generic,NaN,3.0,5,"['Electronics', 'Computers & Accessories', 'Co...",https://m.media-amazon.com/images/I/41wOFaeAMa...,Title: Cool Dealheroes 2.4G Wireless PC game M...,NaN
1,1,wireless gaming mouse,exact,2,0.776168,18a4bd6c-e842-4490-b2cf-bbc231fb4d14,B07338LDKF,Logitech G703 Lightspeed Wireless Gaming Mouse...,LogitechG,129.99,4.1,612,[],https://m.media-amazon.com/images/I/31Zbzsy6Xn...,Title: Logitech G703 Lightspeed Wireless Gamin...,NaN
2,1,wireless gaming mouse,exact,3,0.775496,22de11d0-05ec-42fc-96b6-a088d9d3be93,B09WZZ678M,"LED Wireless Mouse,Ergonomic,Muted,Bluetooth,R...",AOGTUNAL,NaN,3.1,13,"['Electronics', 'Computers & Accessories', 'Co...",https://m.media-amazon.com/images/I/41EZBr0MuC...,"Title: LED Wireless Mouse,Ergonomic,Muted,Blue...",NaN
3,1,wireless gaming mouse,exact,4,0.771288,a9aa75e8-3d87-4cd9-a677-e6fc31c1ee50,B072DVFXMT,Gaming Mouse 3200 DPI Wired Programmable 5 But...,Ansot,NaN,3.7,36,[],https://m.media-amazon.com/images/I/41Wpf4WyW5...,Title: Gaming Mouse 3200 DPI Wired Programmabl...,NaN
4,1,wireless gaming mouse,exact,5,0.763242,a5122347-b15b-4d41-a995-10e8eb83ae3b,B01EJC57CU,UKONM Wired Gaming Mouse 5500 DPI 7 Button LED...,"Shenzhen Ukonm Technology Co.,Ltd",NaN,4.0,14,[],https://m.media-amazon.com/images/I/51IJuX9L8k...,Title: UKONM Wired Gaming Mouse 5500 DPI 7 But...,NaN

In [4]:
df.shape

(800, 16)

In [5]:
df['query_type'].value_counts()

query_type
exact               200
attribute           200
intent              200
natural_language    200
Name: count, dtype: int64

In [6]:
sample_df = df[df['query_type'] == 'natural_language']

In [7]:
sample_df.head()

,query_id,query,query_type,rank,score,id,parent_asin,title,brand,price,rating,rating_count,categories,image_url,document,relevance
600,31,I need a mouse that I can use without a cable,natural_language,1,0.751125,dcccbf65-5d0c-4f06-bf2c-1480d725a035,B00MPFY1FS,Mini USB Retractable Cable Optical Mouse for P...,Generic,NaN,2.0,1,[],https://m.media-amazon.com/images/I/31dCvJ4IUJ...,Title: Mini USB Retractable Cable Optical Mous...,NaN
601,31,I need a mouse that I can use without a cable,natural_language,2,0.731648,2c3d798b-55da-4f44-a811-31e9e306eb0b,B007T9RG84,SM-5000M Gunmetal Blue Double Scroll Wheel Sil...,NaN,NaN,2.9,18,[],https://m.media-amazon.com/images/I/41jzcbrLMK...,Title: SM-5000M Gunmetal Blue Double Scroll Wh...,NaN
602,31,I need a mouse that I can use without a cable,natural_language,3,0.727327,21e95094-a0f6-40d7-ae4a-c01cba00c485,B07KLWM3ZT,Ergonomic Optical Mouse USB High Precision Opt...,All luckly,NaN,3.6,6,[],https://m.media-amazon.com/images/I/41bAaqeEy9...,Title: Ergonomic Optical Mouse USB High Precis...,NaN
603,31,I need a mouse that I can use without a cable,natural_language,4,0.721072,2db9ef8d-ce2a-46ee-9edd-d91edc5e70fb,B08RZ9H9BR,2.4G Ergonomic Portable USB Wireless Mouse for...,KAWAMOUSE,NaN,1.0,1,"['Electronics', 'Computers & Accessories', 'Co...",https://m.media-amazon.com/images/I/51GyNfODiC...,Title: 2.4G Ergonomic Portable USB Wireless Mo...,NaN
604,31,I need a mouse that I can use without a cable,natural_language,5,0.720826,ac906876-ef40-4b2a-80c1-69ad57b7dcbd,B00P95F5L0,Wired Vertical Mouse Mice Ergonomic Design for...,usbkingdom,NaN,4.5,2,"['Electronics', 'Computers & Accessories', 'Co...",https://m.media-amazon.com/images/I/41weSIlVK9...,Title: Wired Vertical Mouse Mice Ergonomic Des...,NaN

In [8]:
eval_data = pd.read_csv('/Users/tusharrohilla/Desktop/natural_language_search_engine/eval_data/evaluation_data_labeled.csv')

In [9]:
eval_data.head()

,query_id,query,query_type,rank,score,id,parent_asin,title,brand,price,rating,rating_count,categories,image_url,document,relevance
0,1,wireless gaming mouse,exact,1,0.788320,c8e08be5-ec7e-4ff4-846a-fa3dd40fddd9,B006VP9R6Q,Cool Dealheroes 2.4G Wireless PC game Mouse Fo...,Generic,NaN,3.0,5,"['Electronics', 'Computers & Accessories', 'Co...",https://m.media-amazon.com/images/I/41wOFaeAMa...,Title: Cool Dealheroes 2.4G Wireless PC game M...,2
1,1,wireless gaming mouse,exact,2,0.776168,18a4bd6c-e842-4490-b2cf-bbc231fb4d14,B07338LDKF,Logitech G703 Lightspeed Wireless Gaming Mouse...,LogitechG,129.99,4.1,612,[],https://m.media-amazon.com/images/I/31Zbzsy6Xn...,Title: Logitech G703 Lightspeed Wireless Gamin...,2
2,1,wireless gaming mouse,exact,3,0.775496,22de11d0-05ec-42fc-96b6-a088d9d3be93,B09WZZ678M,"LED Wireless Mouse,Ergonomic,Muted,Bluetooth,R...",AOGTUNAL,NaN,3.1,13,"['Electronics', 'Computers & Accessories', 'Co...",https://m.media-amazon.com/images/I/41EZBr0MuC...,"Title: LED Wireless Mouse,Ergonomic,Muted,Blue...",2
3,1,wireless gaming mouse,exact,4,0.771288,a9aa75e8-3d87-4cd9-a677-e6fc31c1ee50,B072DVFXMT,Gaming Mouse 3200 DPI Wired Programmable 5 But...,Ansot,NaN,3.7,36,[],https://m.media-amazon.com/images/I/41Wpf4WyW5...,Title: Gaming Mouse 3200 DPI Wired Programmabl...,2
4,1,wireless gaming mouse,exact,5,0.763242,a5122347-b15b-4d41-a995-10e8eb83ae3b,B01EJC57CU,UKONM Wired Gaming Mouse 5500 DPI 7 Button LED...,"Shenzhen Ukonm Technology Co.,Ltd",NaN,4.0,14,[],https://m.media-amazon.com/images/I/51IJuX9L8k...,Title: UKONM Wired Gaming Mouse 5500 DPI 7 But...,2

In [10]:
eval_data['relevance'].value_counts()

relevance
2    587
1    177
0     36
Name: count, dtype: int64

In [11]:
sample_eval_df = eval_data[eval_data['query_type'] == 'natural_language']

In [12]:
sample_eval_df.head()

,query_id,query,query_type,rank,score,id,parent_asin,title,brand,price,rating,rating_count,categories,image_url,document,relevance
600,31,I need a mouse that I can use without a cable,natural_language,1,0.751125,dcccbf65-5d0c-4f06-bf2c-1480d725a035,B00MPFY1FS,Mini USB Retractable Cable Optical Mouse for P...,Generic,NaN,2.0,1,[],https://m.media-amazon.com/images/I/31dCvJ4IUJ...,Title: Mini USB Retractable Cable Optical Mous...,1
601,31,I need a mouse that I can use without a cable,natural_language,2,0.731648,2c3d798b-55da-4f44-a811-31e9e306eb0b,B007T9RG84,SM-5000M Gunmetal Blue Double Scroll Wheel Sil...,NaN,NaN,2.9,18,[],https://m.media-amazon.com/images/I/41jzcbrLMK...,Title: SM-5000M Gunmetal Blue Double Scroll Wh...,1
602,31,I need a mouse that I can use without a cable,natural_language,3,0.727327,21e95094-a0f6-40d7-ae4a-c01cba00c485,B07KLWM3ZT,Ergonomic Optical Mouse USB High Precision Opt...,All luckly,NaN,3.6,6,[],https://m.media-amazon.com/images/I/41bAaqeEy9...,Title: Ergonomic Optical Mouse USB High Precis...,1
603,31,I need a mouse that I can use without a cable,natural_language,4,0.721072,2db9ef8d-ce2a-46ee-9edd-d91edc5e70fb,B08RZ9H9BR,2.4G Ergonomic Portable USB Wireless Mouse for...,KAWAMOUSE,NaN,1.0,1,"['Electronics', 'Computers & Accessories', 'Co...",https://m.media-amazon.com/images/I/51GyNfODiC...,Title: 2.4G Ergonomic Portable USB Wireless Mo...,2
604,31,I need a mouse that I can use without a cable,natural_language,5,0.720826,ac906876-ef40-4b2a-80c1-69ad57b7dcbd,B00P95F5L0,Wired Vertical Mouse Mice Ergonomic Design for...,usbkingdom,NaN,4.5,2,"['Electronics', 'Computers & Accessories', 'Co...",https://m.media-amazon.com/images/I/41weSIlVK9...,Title: Wired Vertical Mouse Mice Ergonomic Des...,1

In [13]:
metric_query_type = pd.read_csv('/Users/tusharrohilla/Desktop/natural_language_search_engine/eval_data/results/metrics_by_query_type.csv')

In [14]:
metric_query_type

,query_type,ndcg@5,mrr@5,recall@5,precision@5,hit_rate@5,ndcg@10,mrr@10,recall@10,precision@10,hit_rate@10,ndcg@20,mrr@20,recall@20,precision@20,hit_rate@20
0,attribute,0.823642,0.833333,0.222744,0.86,0.9,0.820575,0.833333,0.452632,0.87,0.9,0.866431,0.833333,0.9,0.865,0.9
1,exact,1.000000,1.000000,0.250000,1.00,1.0,0.995759,1.000000,0.500000,1.00,1.0,0.999067,1.000000,1.0,1.000,1.0
2,intent,0.830845,1.000000,0.253947,1.00,1.0,0.871488,1.000000,0.507895,1.00,1.0,0.934725,1.000000,1.0,0.985,1.0
3,natural_language,0.625599,1.000000,0.252623,0.98,1.0,0.739470,1.000000,0.505865,0.98,1.0,0.855652,1.000000,1.0,0.970,1.0

In [15]:
metric_query_wise = pd.read_csv('/Users/tusharrohilla/Desktop/natural_language_search_engine/eval_data/results/metrics_per_query.csv')

In [16]:
metric_query_wise

,query_id,query,query_type,num_results,num_relevant,num_highly_relevant,ndcg@5,mrr@5,recall@5,precision@5,...,ndcg@10,mrr@10,recall@10,precision@10,hit_rate@10,ndcg@20,mrr@20,recall@20,precision@20,hit_rate@20
0,1,wireless gaming mouse,exact,20,20,19,1.000000,1.000000,0.250000,1.0,...,0.957586,1.000000,0.500000,1.0,1.0,0.994058,1.000000,1.0,1.00,1.0
1,2,mechanical gaming keyboard,exact,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
2,3,bluetooth headphones,exact,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
3,4,4K HDMI cable,exact,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
4,5,USB C hub,exact,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
5,6,wireless webcam,exact,20,20,0,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
6,7,laptop cooling pad,exact,20,20,19,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,0.996615,1.000000,1.0,1.00,1.0
7,8,computer speakers,exact,20,20,19,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
8,9,external hard drive,exact,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
9,10,gaming monitor,exact,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
10,11,wireless mouse with rechargeable battery,attribute,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
11,12,mechanical keyboard with RGB backlight,attribute,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
12,13,noise cancelling wireless headphones,attribute,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
13,14,4K monitor with HDMI port,attribute,20,14,10,0.333800,0.333333,0.214286,0.6,...,0.454081,0.333333,0.500000,0.7,1.0,0.720822,0.333333,1.0,0.70,1.0
14,15,USB C hub with multiple ports,attribute,20,20,19,1.000000,1.000000,0.250000,1.0,...,0.955831,1.000000,0.500000,1.0,1.0,0.992900,1.000000,1.0,1.00,1.0
15,16,wireless headphones with microphone,attribute,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
16,17,gaming mouse with programmable buttons,attribute,20,19,11,0.902621,1.000000,0.263158,1.0,...,0.795841,1.000000,0.526316,1.0,1.0,0.950587,1.000000,1.0,0.95,1.0
17,18,portable laptop stand with adjustable height,attribute,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
18,19,webcam with built in microphone,attribute,20,0,0,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.00,0.0
19,20,external hard drive with large storage capacity,attribute,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
20,21,mouse for competitive gaming,intent,20,19,17,0.902621,1.000000,0.263158,1.0,...,0.936808,1.000000,0.526316,1.0,1.0,0.979167,1.000000,1.0,0.95,1.0
21,22,keyboard for programming,intent,20,20,2,0.474768,1.000000,0.250000,1.0,...,0.582103,1.000000,0.500000,1.0,1.0,0.778771,1.000000,1.0,1.00,1.0
22,23,headphones for travelling,intent,20,20,14,0.912530,1.000000,0.250000,1.0,...,0.890972,1.000000,0.500000,1.0,1.0,0.965355,1.000000,1.0,1.00,1.0
23,24,monitor for working from home,intent,20,19,2,0.474768,1.000000,0.263158,1.0,...,0.744648,1.000000,0.526316,1.0,1.0,0.801792,1.000000,1.0,0.95,1.0
24,25,webcam for video conferencing,intent,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
25,26,speakers for watching movies,intent,20,19,17,0.857342,1.000000,0.263158,1.0,...,0.907425,1.000000,0.526316,1.0,1.0,0.957575,1.000000,1.0,0.95,1.0
26,27,storage device for backing up photos,intent,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
27,28,USB hub for connecting laptop accessories,intent,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
28,29,cooling pad for a gaming laptop,intent,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
29,30,headphones for listening to music,intent,20,20,11,0.686423,1.000000,0.250000,1.0,...,0.652921,1.000000,0.500000,1.0,1.0,0.864590,1.000000,1.0,1.00,1.0
30,31,I need a mouse that I can use without a cable,natural_language,20,20,14,0.430712,1.000000,0.250000,1.0,...,0.630571,1.000000,0.500000,1.0,1.0,0.821447,1.000000,1.0,1.00,1.0
31,32,I want a keyboard that is good for long hours ...,natural_language,20,18,3,0.408922,1.000000,0.277778,1.0,...,0.656022,1.000000,0.555556,1.0,1.0,0.761247,1.000000,1.0,0.90,1.0
32,33,I need headphones that block outside noise whi...,natural_language,20,20,3,0.408922,1.000000,0.250000,1.0,...,0.596902,1.000000,0.500000,1.0,1.0,0.776968,1.000000,1.0,1.00,1.0
33,34,I want to connect my laptop to a 4K television,natural_language,20,19,12,0.573370,1.000000,0.263158,1.0,...,0.615356,1.000000,0.473684,0.9,1.0,0.842156,1.000000,1.0,0.95,1.0
34,35,I need something that lets me connect several ...,natural_language,20,20,5,0.631236,1.000000,0.250000,1.0,...,0.755811,1.000000,0.500000,1.0,1.0,0.838706,1.000000,1.0,1.00,1.0
35,36,I want a monitor that is comfortable for progr...,natural_language,20,20,6,0.430712,1.000000,0.250000,1.0,...,0.602479,1.000000,0.500000,1.0,1.0,0.781091,1.000000,1.0,1.00,1.0
36,37,I need a webcam for online meetings and video ...,natural_language,20,20,19,1.000000,1.000000,0.250000,1.0,...,0.953713,1.000000,0.500000,1.0,1.0,0.991503,1.000000,1.0,1.00,1.0
37,38,I want something to keep my gaming laptop from...,natural_language,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0
38,39,I need extra storage to back up my photos and ...,natural_language,20,17,5,0.372114,1.000000,0.235294,0.8,...,0.583848,1.000000,0.529412,0.9,1.0,0.743405,1.000000,1.0,0.85,1.0
39,40,I want speakers that are good for watching mov...,natural_language,20,20,20,1.000000,1.000000,0.250000,1.0,...,1.000000,1.000000,0.500000,1.0,1.0,1.000000,1.000000,1.0,1.00,1.0

In [4]:
df1 = pd.read_csv('/Users/tusharrohilla/Desktop/natural_language_search_engine/eval_data/reranked_results/metrics_by_query_type.csv')

In [5]:
df2 = pd.read_csv('/Users/tusharrohilla/Desktop/natural_language_search_engine/eval_data/results/metrics_by_query_type.csv')

In [6]:
df1

,query_type,ndcg@5,mrr@5,recall@5,precision@5,hit_rate@5,ndcg@10,mrr@10,recall@10,precision@10,hit_rate@10,ndcg@20,mrr@20,recall@20,precision@20,hit_rate@20
0,attribute,0.866084,0.850000,0.229887,0.88,0.9,0.859513,0.850000,0.454511,0.87,0.9,0.881656,0.850000,0.9,0.865,0.9
1,exact,1.000000,1.000000,0.250000,1.00,1.0,1.000000,1.000000,0.500000,1.00,1.0,0.999784,1.000000,1.0,1.000,1.0
2,intent,0.954897,1.000000,0.253947,1.00,1.0,0.945988,1.000000,0.502632,0.99,1.0,0.973347,1.000000,1.0,0.985,1.0
3,natural_language,0.754808,0.933333,0.246741,0.96,1.0,0.804408,0.933333,0.499983,0.97,1.0,0.899633,0.933333,1.0,0.970,1.0

In [7]:
df2

,query_type,ndcg@5,mrr@5,recall@5,precision@5,hit_rate@5,ndcg@10,mrr@10,recall@10,precision@10,hit_rate@10,ndcg@20,mrr@20,recall@20,precision@20,hit_rate@20
0,attribute,0.823642,0.833333,0.222744,0.86,0.9,0.820575,0.833333,0.452632,0.87,0.9,0.866431,0.833333,0.9,0.865,0.9
1,exact,1.000000,1.000000,0.250000,1.00,1.0,0.995759,1.000000,0.500000,1.00,1.0,0.999067,1.000000,1.0,1.000,1.0
2,intent,0.830845,1.000000,0.253947,1.00,1.0,0.871488,1.000000,0.507895,1.00,1.0,0.934725,1.000000,1.0,0.985,1.0
3,natural_language,0.625599,1.000000,0.252623,0.98,1.0,0.739470,1.000000,0.505865,0.98,1.0,0.855652,1.000000,1.0,0.970,1.0